name: Update the Main Docs Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update-main-docs:
    uses: validityBase/vbase-github-actions/.github/workflows/publish-docs.yml@v1
    with:
      python-version: "3.12"
      requirements-files: |
        requirements/lock/docs.txt
      require-hashes: true
      pre-publish-command: |
        set -euo pipefail
        sphinx-build -b markdown docs/ docs/_build/markdown
        sed -i 's/vbase_api\.vbase_api_client\.VBaseAPIClient/vbase_api\.VBaseAPIClient/g' docs/_build/markdown/vbase_api_client.md
        sed -i 's/vbase_api\.vbase_api_models/vbase_api/g' docs/_build/markdown/vbase_api_models.md
      source-docs-path: docs/_build/markdown
      target-repository-branch: main
    secrets:
      DOCS_REPO_ACCESS_TOKEN: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }}
